// <auto-generated />
namespace HTTP5212_Passion_Project3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class comment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(comment));
        
        string IMigrationMetadata.Id
        {
            get { return "202302092322131_comment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
